In [110]:
################################################
#I'm going to find an orthogonal basis for the space V with the normal
#basis of {v_1, v_2, ... , v_k}. In order to do that I'm going to
#implement the Gram-Schmidt process by using numpy package.
#So here we go ...
################################################

In [5]:
import numpy as np

#Since I use normalized vectors frequently in this algorithm,
#here is a function which calculates the normalized vector.
def normalize(v):
    return v/np.linalg.norm(v)

#Also I will define a function which will compute the projection of  
#vector v on subspace w.
#The projection of a vector like a on a subspace like b with the basis
#like {b_1, b_2, b_3, ..., b_n} is equal to 
#//Summation of (((b_i)dot product a)/norm(b_i))*((b_i)/(norm(b_i))) for (1<=i<=n)//
def projection(v,w):
    projection_result = sum(np.dot(v,vec)*np.array(vec) for vec in w)
    return projection_result

In [6]:
#Gram-Schmidt main algorithm:
#we can say that V_1 is a subspace of V with basis of v_1 i.e.:
#V_1 = span(v_1) = span(u_1) where u_1 is the normalized vector of v_1

#for two dimensional space like V_2 we would have:
#V_2 = span(v_1, v_2) = span(u_1, v_2) where v_2 must be orthogonal with
#respect to u_1. So, I can say that there is a vector like y_2 such that
#y_2 = v_2 - projection of v_2 on V_1 
#and y_2 is orthogonal to V_1 and also orthogonal to u_1

#Since I need an orthonormal basis I will have u_2 = y_2/norm(y_2)
#this procedure will be repeated until the subspace V_k which is equivalent with V.
#here is the code:
def gram_schmidt(V):
    U = [normalize(V[0])]
    #print(len(V))
    for v in V:
        w = v - projection(v, U)
        if np.linalg.norm(w)>0: 
            U.append(normalize(w))
    if len(U)==1:
        return np.array(U)
    else:
        return np.array(U[1:])
    

In [7]:
#I'm going to set the number of vectors in basis of V and number of 
#elements in each vector
NUMBER = np.random.randint(1, 1000)
ELEMENTS = np.random.randint(1, 1000)

#First of all we should have an array of vectors which is the basic
#type of basis for space like V:
basic_basis = np.random.rand(NUMBER,ELEMENTS)
print("The basic basis for V is :")
print(basic_basis)
print("-"*100)
#Here is my ORTHONORMAL basis for V:
orthonormal_basis = gram_schmidt(basic_basis)
print("Orthonormal basis for V is :")
print(orthonormal_basis)

The basic basis for V is :
[[0.61305681 0.36567593 0.68233065 ... 0.12714131 0.35296766 0.7913573 ]
 [0.35389723 0.58523801 0.11594229 ... 0.68425932 0.5423427  0.00107425]
 [0.41963021 0.02520322 0.4213293  ... 0.89277879 0.07525891 0.18815785]
 ...
 [0.47137849 0.96884552 0.79405974 ... 0.67290945 0.73617864 0.7796742 ]
 [0.94814387 0.13464075 0.02449699 ... 0.22329226 0.87526691 0.12399577]
 [0.98718892 0.06905377 0.29350259 ... 0.20807483 0.77082121 0.15523622]]
----------------------------------------------------------------------------------------------------
Orthonormal basis for V is :
[[ 0.          0.          0.         ...  0.          0.
  -0.14961717]
 [-0.00813332  0.04227244 -0.04405959 ...  0.07525195  0.03796233
  -0.04911542]
 [ 0.00029671 -0.05160976  0.01001815 ...  0.07410281 -0.0416439
  -0.02004582]
 ...
 [-0.04837426 -0.09215356  0.08740079 ... -0.03221386 -0.06782296
  -0.04651515]
 [-0.04656549 -0.09352245  0.08807066 ... -0.0326941  -0.06947324
  -0.04601488